services:
  db:
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: 'expensetracker'
      POSTGRES_USER: 'spring'
      POSTGRES_PASSWORD: 'spring'
    ports:
      - '5433:5432'  # Changed port

